on: '2'
services:
  pg_server:
    image: sameersbn/postgresql:10-2
    restart: always
    ports:
      - 54321:5432
    volumes:
      - ./database:/var/lib/postgresql
    enviroment:
      - DEBUG=false
      - DB_USER= odoo     #the user can login in the server
      - DB_PASS= test@123
